### ISSUE TITLE
No se ejecuta dev/bd/poblar

### ISSUE THREAD

**Issue by cebraSpA** [LibreDTE/libredte-webapp#1]
Hola, gracias por poner a disposición tu gran trabajo, hemos instalado el cliente web en nuestro servidor sin problemas, pero al querer importar los datos de actividades económicas y division geopolítica nos devuelve el siguiente error

Página de error
Se ha capturado la excepción sowerphp\core\Exception_Controller_Missing y la página web a dejado de ser ejecutada. El error fue:

Controlador Controller_Dev no fue encontrado
En la siguiente traza puede encontrar información útil para resolver el problema:

#0 DIR_WEBSITE/webroot/index.php(52): sowerphp\core\Routing_Dispatcher::dispatch()
#1 {main}
Por favor verifique que la dirección web que lo trajo a esta página sea válida.

agradecería mucho que nos ayudasen a solucionar este problema?

Cristian Droguett, Cebra SpA.

**Comment by estebandelaf** [comment]
Hola,

No tienes cargado el módulo, debes incluir a "Dev" en los módulos que la aplicación usa en el archivo de configuración Config/core.php

El módulo Dev se carga automáticamente sólo si la aplicación se encuentra en un ambiente de desarrollo[1], y este ambiente de desarrollo sólo se asigna si la variable de entorno de apache APPLICATION_ENV tiene el valor "dev"[2]. Como supongo no tienes configurada dicha variable de entorno es que el framework funciona en ambiente "producción" y no carga el módulo Dev. Dicho módulo no es recomendable usarlo en producción ya que tiene opciones "peligrosas", por eso sólo es cargado automáticamente bajo esta condición.

Agradecería confirmar que tu problema queda solucionado para cerrar la issue.

Saludos!

[1] https://github.com/SowerPHP/extension-app/blob/master/Config/core.php#L25
[2] https://github.com/SowerPHP/sowerphp/blob/master/lib/sowerphp/core/bootstrap.php#L55

**Comment by cebraSpA** [comment]
Se ha resuelto el problema, gracias por tu ayuda Esteban.
