### ISSUE TITLE
Object como palabra reservada en PHP 7.2

### ISSUE THREAD

**Issue by diegosep** [LibreDTE/libredte-webapp#10]
Hola, en la extension app del proyecto hay una clase llamada Object, eso desde PHP 7.2  es palabra reservada, asi que en mi local corregí el uso de esto a un "PHPObject"

Estoy revisando el sistema, si funciona creo un PR.

**Comment by estebandelaf** [comment]
Abrir issue en repositorio que corresponda y se revisará y corregirá, se cierra en este repositorio por no corresponder aquí.
