### ISSUE TITLE
Registro de compras y ventas

### ISSUE THREAD

**Issue by diegosep** [LibreDTE/libredte-webapp#11]
Hola, escribo para consultar si hay alguna actualización en el sistema respecto al registro de compras y ventas, Segun el SII el (IECV) fue reemplazado por el RCV, que es mas simple.

Saludos.

**Comment by estebandelaf** [comment]
Existe desde versión 20170918.

https://blog.libredte.cl/index.php/2017/09/18/version-libredte-20170918/
