### ISSUE TITLE
Error al levantar la aplicación.

### ISSUE THREAD

**Issue by DonNicoCordova** [LibreDTE/libredte-webapp#13]
Levantando la aplicación web y siguiendo el manual paso a paso, me entrega el siguiente error al intentar de acceder:

[Thu Dec 20 19:12:35.531375 2018] [:error] [pid 9826] [client 10.0.2.2:55590] PHP Warning:  include(): Filename cannot be empty in /usr/share/sowerphp/lib/sowerphp/core/View/Helper/Pages/Php.php on line 46

Junto con esto sólo se muestra una pantalla blanca. 

SO: Ubuntu 16.04
PHP: 7.0.32
Servidor: Apache2
 
Hay alguna configuración extra que debo hacer y que no aparece actualmente en el manual?

EDIT:
Adjunto imagen del archivo Php.php correspondiente al error.
![screen shot 2018-12-20 at 4 38 57 pm](https://user-images.githubusercontent.com/39866195/50307000-d7d11780-0475-11e9-96ce-e8af4418b4b4.png)

**Comment by estebandelaf** [comment]
El error es probable que se deba a que la versión actual del framework SowerPHP no es compatible con la versión actualmente liberada de LibreDTE (el framework va más adelante).

Tendrías que esperar a que se libere la próxima versión de LibreDTE.

**Comment by DonNicoCordova** [comment]
Gracias por tu respuesta!, igual comprendo que la próxima versión LibreDTE se puede demorar en salir, hay alguna forma de talvez hacer un downgrade a la versión que tengo de SowerPHP para poder utilizar la versión actual de LibreDTE.

**Comment by estebandelaf** [comment]
La próxima semana se publicará una nueva versión, ahí podrá instalar sin problemas.

**Comment by DonNicoCordova** [comment]
Muchas gracias.

**Comment by estebandelaf** [comment]
Se publicó la versión 20190101.
