### ISSUE TITLE
Error de Instalación

### ISSUE THREAD

**Issue by neowolfman** [LibreDTE/libredte-webapp#14]
Luego de instalar en una maquina virtual desde 0, siguiendo el manual de instalación quedo con este error al abrir la pagina desde el navegador.

Warning: require(Vendor/autoload.php): failed to open stream: No such file or directory in /usr/share/sowerphp/extensions/sowerphp/general/bootstrap.php on line 25

Fatal error: require(): Failed opening required 'Vendor/autoload.php' (include_path='.:/usr/share/php') in /usr/share/sowerphp/extensions/sowerphp/general/bootstrap.php on line 25

**Comment by estebandelaf** [comment]
Falta ejecutar composer
