### ISSUE TITLE
No puedo Generar un DTE desde WebApp

### ISSUE THREAD

**Issue by falvarezh90** [LibreDTE/libredte-webapp#15]
Al momento de querer generar un DTE desde la webapp, en particular una factura electrónica, me aparece el siguiente mensaje de error:

` danger: No fue posible guardar el DTE temporal: 23502 7 ERROR: null value in column "usuario" violates not-null constraint DETAIL: Failing row contains (17295365, 11111111, 33, 90b1c7ee64fde27f0e0b2f422cadf4b7, 2019-11-14, 56525, {"Encabezado":{"IdDoc":{"TipoDTE":"33","Folio":0,"FchEmis":"2019..., null, null). INSERT INTO dte_tmp ( emisor, receptor, dte, codigo, fecha, total, datos ) VALUES ( :emisor, :receptor, :dte, :codigo, :fecha, :total, :datos ) `

Al parecer falta enviar el dato del usuario, pero no se si es un error de frontend o backend, o quizás me faltó realizar alguna configucación adicional.

**Comment by estebandelaf** [comment]
Por lo general ese tipo de errores ocurre al tener una instalación hecha de manera errónea.

Se recomienda verificar el proceso de instalación.
