### ISSUE TITLE
Trying to access array offset on value of type null in /usr/share/sowerphp/lib/sowerphp/core/View.php on line 71

### ISSUE THREAD

**Issue by cfficaurzua** [LibreDTE/libredte-webapp#17]
Hola instalé libredte siguiendo las instrucciones del manual pero para poblar me pide que ingresé, cuando ingreso usuario "admin:admin"
Me aparece el siguiente error
Trying to access array offset on value of type null in /usr/share/sowerphp/lib/sowerphp/core/View.php on line 71
Y
Notice: Trying to access array offset on value of type null in /usr/share/sowerphp/lib/sowerphp/core/View.php on line 124

Revisando es cuando intenta leer $requests.params["modules"]
El sistema está bajo apache2 con un proxy de nginx

Ubuntu 18.04.4 LTS
Php 7.3.17

Alguna solución?
Gracias

**Comment by estebandelaf** [comment]
Es altamente probable que sea algún error en la instalación.

Como norma, verificar que la distribución sea la recomendada (Debian GNU/Linux 10 de 64 bits). Y que esté todo actualizado, tanto framework como libredte.

**Comment by cfficaurzua** [comment]
Hola, 
Reinstalé todo en otro server ahora con Debian 10.3 x64 (limpio) 
siguiendo las instrucciones para instalar el framework que dice: php5 (se recomienda php7)
por lo que opte por 
PHP 7.4
apache 2.4.43
Composer
Git
Mercurial
PostgreSQL, se configura base de datos con usuario libredte y clave
instalación librerias pear, curl, imap,  soap, etc
pear Mail, Mail_mime_ net_smtp
Se configura core.php y routes.php con todo lo requerido
Se cargan los schemas, 
Se configura apache con AllowOverride All para el directorio
se actualiza sowerpkg y libredte 

Se intenta poblar y luego de enviar formulario de en la página usuarios -> ingresar,  con usuario:admin , pass: admin, sale el mismo error.
hay algo que no esté en la documentación?

**Comment by AlbertoGalleguillosAcid** [comment]
Hola @cfficaurzua estoy en la misma situación que tú, pudiste solucionarlo ?

**Comment by cfficaurzua** [comment]
No me acuerdo mucho, pero creo que fallaba al poblar la base de datos. 
había que aumentar la memoria e intentarlo de nuevo.
Puedes usar swap file en linux para eso.

Lo que si me paso, que tuve que modificar por que había un bug que no dejaba descargar los archivos (pdf, zip)
en el archivo website/Vendor/sasco/libredte/lib/File.php tuve que agregar la línea
ob_end_flush(); luego de ob_clean(); [pero eso es de otro repositorio]

```
@@ -154,12 +158,15 @@ class File
             // escribir en el sistema de archivos y cerrar archivo
             file_put_contents($dir.DIRECTORY_SEPARATOR.$file_compressed, $zip->getStream(md5($filepath)));
             $zip->close();
+
         } else {
             exec('cd '.$dir.' && '.str_replace(':in', $file, $options['commands'][$options['format']]));
         }
         // enviar archivo
+
         if ($options['download']) {
             ob_clean();
+            ob_end_flush();
             header ('Content-Disposition: attachment; filename='.$file_compressed);
```
Saludos.
