### ISSUE TITLE
Manual installation not working

### ISSUE THREAD

**Issue by AsServices** [LibreDTE/libredte-webapp#19]
First of all, thank you for this amazing web!
i followed the document https://github.com/LibreDTE/libredte-webapp/blob/master/INSTALL.md for instaltion. after that i visit my web URL in browser it's showing only the following page without any css ( nay other route geting 404 )

![LibreDTE](https://user-images.githubusercontent.com/45225321/116324614-11e91b80-a7de-11eb-917b-df6cf4869ffe.png)

Specifications 
Debian 9
Apache 2
PHP 7.3

and also can we see how virtualhost will look like for apatche2?
also if you provide video tutorial for installation then its very grateful & thankful

Thank you

**Comment by estebandelaf** [comment]
La aplicación está probada en Debian GNU/Linux 10, la versión 9 ya no tiene soporte.

Respecto al error, quizás te falta algún paso de apache o mod_rewrite.

No hay tutoriales adicionales ni videos.

Si requieren el servicio de instalación y soporte, pueden solicitarlo en https://libredte.cl/ventas/dte-local
