### ISSUE TITLE
Puntos en Rut

### ISSUE THREAD

**Issue by Adoniasv** [LibreDTE/libredte-webapp#2]
Hola

Cuando generas el intercambio de archivos para el SII, te da un error de Schema.

Esto es porque en cuando genera la caratula, no limpia los puntos del rut. 

rutresponde XX.XXX.XXX-X

**Comment by estebandelaf** [comment]
Hola!,

Primero, asumiré que te refieres a la biblioteca de LibreDTE y no a la webapp (donde has reportado la issue). En dicho caso eso es correcto lo que sucede, ya que en general no se hacen validaciones de los datos. La biblioteca básicamente se preocupa de: normalizar, construir el XML, timbrar/firmar y enviar al SII, pero todo lo anterior asumiendo que los datos son correctos. Las validaciones que desees hacer tendrías que hacerlas en la aplicación que hace uso de la biblioteca.

En el módulo de LibreDTE (módulo que es parte de la webapp) tampoco se hacen dichas validaciones en el caso del intercambio, esto porque los datos, como el RUT, son sacados directamente de los XML recibido, donde ya vienen correctos.

Un ejemplo más extremo, la biblioteca no valida por ejemplo que el monto ingresado sea un monto efectivamente (un número), podrías perfectamente ingresar una letra y el XML se generaría. Por la misma razón es que antes de generar el XML se valida el esquema. El esquema es entregado por el SII y ya contiene todas las validaciones necesarias.

Entiendo que tu pregunta va por el hecho de "corregir el dato", más que sólo validarlo. Pero como mencioné antes, esa es labor de la app que usa la biblioteca.

Saludos!
