### ISSUE TITLE
Problema en Emision masiva

### ISSUE THREAD

**Issue by truchosky** [LibreDTE/libredte-webapp#23]
con un csv correcto no se pueden generar los documento, libredte retorna el resultado con el código de error 4 (no fue posible emitir el dte temporal), mismo csv pero ejecutado desde cliente python funciona

**Comment by estebandelaf** [comment]
Error 4 es probablemente un error de formato. Se recomienda revisar el error si es que se obtiene correo con resultado.

**Comment by estebandelaf** [comment]
No son las mismas funcionalidades, son archivos similares, pero no son procesados igual.

**Comment by estebandelaf** [comment]
Te recomiendo abrir un ticket de soporte en https://libredte.cl/soporte (en caso que tengas soporte con nosotros). Así te pueden ayudar con tu caso específico. El archivo no ha cambiado, es compatible hacia atrás siempre.

**Comment by truchosky** [comment]
entonces definitivamente es un problema con la actualización

**Comment by estebandelaf** [comment]
No necesariamente, nuestros usuarios de libredte.cl no han reportado problema con esa utilidad y la actualización es de octubre 2021. Por eso, para quienes son clientes, les pedimos que abran una solicitud de soporte, así revisamos bien el caso con más antecedentes.
