### ISSUE TITLE
datepicker error

### ISSUE THREAD

**Issue by truchosky** [LibreDTE/libredte-webapp#27]
nunca me había fijado, no se si siempre ha sido así o apareció en las ultimas actualizaciones pero la consulta de documentos no permite elegir la fecha, el error que muestra chrome es
![image](https://user-images.githubusercontent.com/9977546/203572193-b139a3bc-e0dd-42bd-b29e-8cf4442f251d.png)

**Comment by estebandelaf** [comment]
¿Te refieres a esta vista: `/dte/dte_emitidos/listar` ?

Se probó en una versión comunidad y funciona ok. ¿Quizás has modificado el layout? Podría ser eso si lo hiciste.
