### ISSUE TITLE
No toma los impuestos adicionales y puede producirse descuadre al anular factura

### ISSUE THREAD

**Issue by isos** [LibreDTE/libredte-webapp#3]
Es básicamente lo que comento, al hacer clic en anular factura no se transpasan los impuestos adicionales y se puede producir descuadre al ponerlos manualmente.

**Comment by estebandelaf** [comment]
Corregido: https://github.com/LibreDTE/libredte-sowerphp/commit/06bceed0466f022c65f0a469d9c37ce776c35592
