### ISSUE TITLE
Error al usar la certificación (generación de xml) [Controlador Controller_Utilidades no fue encontrado]

### ISSUE THREAD

**Issue by fnaquira** [LibreDTE/libredte-webapp#30]
Al intentar completar el proceso de certificación, en la etapa de generar XML, se obtiene el siguiente mensaje:

![imagen](https://github.com/LibreDTE/libredte-webapp/assets/2091780/1d908ac9-615a-498d-bca4-d4659fb2c940)

La instalación ha funcionado perfectamente hasta este paso. Acabo de realizarla ahora según el manual tal como estaba, Debian 11, cada comando sin ningún error hasta el momento.
Por si acaso, intenté enviar data incompleta y si responde el servicio, me indica que falta CAF o falta Certificado, pero si envío todo con éxito, da ese mensaje.
¿Hay algún paso adicional? ¿o la ruta para obtener el xml necesita alguna modificación?

**Comment by estebandelaf** [comment]
Es probablemente algo con la configuración. Revisa los módulos cargados.

De todas formas, te recomiendo instalar la versión 21.10 https://github.com/LibreDTE/libredte-webapp/releases/tag/21.10.0

Esa es la última versión que salió y está ok.

La que está en la rama master, está aún sin publicar. Lo tengo pendiente hace tiempo y no se ha hecho, espero publicar la versión 23.10 en el próximo octubre (espero).

**Comment by fnaquira** [comment]
Si, seguí las instrucciones del README y está en la versión 21.10
![imagen](https://github.com/LibreDTE/libredte-webapp/assets/2091780/7368533c-1d52-4e7a-bc62-5e6b72115711)
¿Cómo reviso los módulos cargados?
