### ISSUE TITLE
No puedo encontrar el archivo PostgreSQL.sql

### ISSUE THREAD

**Issue by kkoci** [LibreDTE/libredte-webapp#4]
Hola, estoy siguiendo éste tutorial

[https://github.com/LibreDTE/libredte-webapp/blob/master/INSTALL.md](url)

Pero cuando llego a éste paso:

> psql libredte < libredte/website/Module/Dte/Model/Sql/PostgreSQL.sql

Yo coloco mi ruta, donde tengo clonado el repo de libredte-webapp, con ésa ruta exacta, y no hay ningún archivo PostgreSQL.sql

¿Alguna idea de ésto?

¿Habrá faltado algo al clonarlo?

Yo cloné el repo simplemente con

`git clone https://github.com/LibreDTE/libredte-webapp/`

¿Alguna idea al respecto?

Gracias de antemano.

**Comment by estebandelaf** [comment]
Hola! No seguiste las instrucciones, revisa el paso 1, el comando git que ejecutaste es incorrecto. Saludos!
