### ISSUE TITLE
Instalación en Nginx

### ISSUE THREAD

**Issue by kkoci** [LibreDTE/libredte-webapp#5]
Hola, una pregunta

¿Tienes algún tuto o existe alguno sobre cómo configurar el site en Nginx?

Yo ahora tengo ésta configuración por ponerte un ejemplo:

server {
        listen 80;
        index index.php index.html indext.htm;
        root /usr/share/nginx/html/;
        index index.php index.html index.htm;
        server_name localhost;

```
    location / {
            try_files $uri $uri/ /index.php?$uri&$args;
    }
    error_page 404 /404.html;
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
            root /usr/share/nginx/html/libredte;
    }
location ~ \.php$ {
    fastcgi_pass unix:/var/run/php5-fpm.sock;
    fastcgi_index index.php;
    include fastcgi_params;
}
```

}

Pero como tengo entendio, realmente el index.php está en /libredte/website/webroot/

¿Será ésa la ruta como root de la app?

De antemano Gracias

**Comment by estebandelaf** [comment]
Hola!,

Con Apache debes usar mod_rewrite, tendrías que hacer algo similar con nginx. He usado nginx pero no para hacer correr LibreDTE.

Es probable que haya que hacer más de algún cambio al framework y proyecto, otros que lo han tratado de hacer al final terminaron usando Apache.

De todas formas si lo logras hacer, publica el fork con los cambios de los proyectos que modifiques para agregarlo a la versión oficial.

Saludos!

PD: dejaré esto abierto un tiempo por si encuentras la solución o bien alguien más la aporta.
