### ISSUE TITLE
Vista DteIntercambios/pdf no encontrada

### ISSUE THREAD

**Issue by mibanez** [LibreDTE/libredte-webapp#7]
Hola,

Al intentar descargar el pdf de cualquier documento recibido (`/dte/dte_intercambios/pdf/...`)
obtengo el siguiente error:

sowerphp\core\Exception_View_Missing y la página web a dejado de ser ejecutada. El error fue:
```
Vista DteIntercambios/pdf para acción DteIntercambios::pdf() no ha sido encontrada
````

El error es producido cuando falla la solicitud al endpoint de generación de pdf (`/api/dte/documentos/generar_pdf`) en el controlador de itercambios `website/Module/Dte/Controller/DteIntercambios.php`:
```
$response = $rest->post($this->request->url.'/api/dte/documentos/generar_pdf', $data);
if ($response['status']['code']!=200) {
    \sowerphp\core\Model_Datasource_Session::message($response['body'], 'error');
    return;
}
```

Añadiendo un redirect o un echo se soluciona. Pero mi problema es que `$response`esta vacío, cualquier intento de imprimir su contenido es vacío. Tampoco `\sasco\LibreDTE\Log::readAll()`.

Aquí me mareo un poco... algún hint sobre como obtener más información sobre este error?
Muchas gracias

**Comment by estebandelaf** [comment]
Hola,

Esa vista no existe intencionalmente (no es que falte), ya que no se usa. En una situación normal (cuando generar_pdf funciona) el sistema entrega el PDF. Como la consulta al servicio web está fallando no entrega el PDF y el framework pide la vista.

Revisa que tengas todo bien instalado, dependencias, curl, ssl, etc. Ya que si response está vacío entonces significa que no se pudo ni siquiera enviar la solicitud HTTP al servicio web. El log de LibreDTE no te mostrará nada, ya que no tiene que ver en este caso (ese log es sólo de la biblioteca, y en la acción que estás no se usa)

Al no ser un bug, no se corrige y esta issue se cerrará, si tienes más dudas puedes consultar en el foro de LibreDTE en https://groups.google.com/forum/#!forum/libredte

Saludos,
