### ISSUE TITLE
INT no es sufcientemnete grande para track_id

### ISSUE THREAD

**Issue by crilam** [LibreDTE/libredte-webapp#8]
Los códigos del seguimiento del SII superaron el límite de la cantidad de dígitos de los INT. Para ello hay que cambiar los INT a BIGINT o similar.

ALTER TABLE dte_boleta_consumo ALTER COLUMN track_id type BIGINT;
ALTER TABLE dte_compra ALTER COLUMN track_id type BIGINT;
ALTER TABLE dte_emitido ALTER COLUMN track_id type BIGINT;
ALTER TABLE dte_emitido ALTER COLUMN cesion_track_id type BIGINT;
ALTER TABLE dte_guia ALTER COLUMN track_id type BIGINT;
ALTER TABLE dte_venta ALTER COLUMN track_id type BIGINT;

**Comment by estebandelaf** [comment]
Esto es parte del módulo Dte, y ya fue parchado en https://github.com/LibreDTE/libredte-modulo-Dte/commit/887fd5b3a14b609bea46a4b65b90e9a1fd683b59
