### ISSUE TITLE
Caracteres maximos permitidos en Teléfono

### ISSUE THREAD

**Issue by ghost** [LibreDTE/libredte-webapp#9]
Hola,

Al modificar un contribuyente en:

`Dte / contribuyentes / modificar`

El maximo de caracteres permitidos para ingresar en el campo de teléfono son 20.

El ejemplo para este campo muestra lo siguiente:

`Ejemplos: celular +56 9 88776655 / Santiago +56 2 22334455 / Santa Cruz +56 72 2821122`

Lo cual claramente es más de 20.

Saludos.

**Comment by estebandelaf** [comment]
El ejemplo es correcto, ya que es UN teléfono, no varios.

**Comment by Rayduxz** [comment]
Entiendo, ¿alguna sugerencia o idea para poner más de uno?
Ej: Varias sucursales.

Saludos.

**Comment by estebandelaf** [comment]
En versión oficial está el módulo CRM que permite colocar más teléfonos, correos, y direcciones. https://libredte.cl/crm/clientes

En versión comunidad, habría que programar un módulo similar. Ahora que hay extensiones es más fácil: https://github.com/LibreDTE/libredte-webapp-ejemplos-extensiones
